import pygame

names = {
    "0": pygame.K_0,
    "1": pygame.K_1,
    "2": pygame.K_2,
    "3": pygame.K_3,
    "4": pygame.K_4,
    "5": pygame.K_5,
    "6": pygame.K_6,
    "7": pygame.K_7,
    "8": pygame.K_8,
    "9": pygame.K_9,

    "a": pygame.K_a,
    "b": pygame.K_b,
    "c": pygame.K_c,
    "d": pygame.K_d,
    "e": pygame.K_e,
    "f": pygame.K_f,
    "g": pygame.K_g,
    "h": pygame.K_h,
    "i": pygame.K_i,
    "j": pygame.K_j,
    "k": pygame.K_k,
    "l": pygame.K_l,
    "m": pygame.K_m,
    "n": pygame.K_n,
    "o": pygame.K_o,
    "p": pygame.K_p,
    "q": pygame.K_q,
    "r": pygame.K_r,
    "s": pygame.K_s,
    "t": pygame.K_t,
    "u": pygame.K_u,
    "v": pygame.K_v,
    "w": pygame.K_w,
    "x": pygame.K_x,
    "y": pygame.K_y,
    "z": pygame.K_z,

    "f1": pygame.K_F1,
    "f2": pygame.K_F2,
    "f3": pygame.K_F3,
    "f4": pygame.K_F4,
    "f5": pygame.K_F5,
    "f6": pygame.K_F6,
    "f7": pygame.K_F7,
    "f8": pygame.K_F8,
    "f9": pygame.K_F9,
    "f10": pygame.K_F10,
    "f11": pygame.K_F11,
    "f12": pygame.K_F12,
    "f13": pygame.K_F13,
    "f14": pygame.K_F14,
    "f15": pygame.K_F15,

    "keypad 0": pygame.K_KP0,
    "keypad 1": pygame.K_KP1,
    "keypad 2": pygame.K_KP2,
    "keypad 3": pygame.K_KP3,
    "keypad 4": pygame.K_KP4,
    "keypad 5": pygame.K_KP5,
    "keypad 6": pygame.K_KP6,
    "keypad 7": pygame.K_KP7,
    "keypad 8": pygame.K_KP8,
    "keypad 9": pygame.K_KP9,
    "keypad /": pygame.K_KP_DIVIDE,
    "keypad enter": pygame.K_KP_ENTER,
    "keypad =": pygame.K_KP_EQUALS,
    "keypad -": pygame.K_KP_MINUS,
    "keypad *": pygame.K_KP_MULTIPLY,
    "keypad .": pygame.K_KP_PERIOD,
    "keypad +": pygame.K_KP_PLUS,

    "up": pygame.K_UP,
    "down": pygame.K_DOWN,
    "left": pygame.K_LEFT,
    "right": pygame.K_RIGHT,

    "left ctrl": pygame.K_LCTRL,
    "right ctrl": pygame.K_RCTRL,
    "left shift": pygame.K_LSHIFT,
    "right shift": pygame.K_RSHIFT,
    "left meta": pygame.K_LMETA,
    "right meta": pygame.K_RMETA,
    "left alt": pygame.K_LALT,
    "right alt": pygame.K_RALT,
    "left super": pygame.K_LSUPER,
    "right super": pygame.K_RSUPER,

    ">": pygame.K_GREATER,
    "<": pygame.K_LESS,
    "[": pygame.K_LEFTBRACKET,
    "]": pygame.K_RIGHTBRACKET,
    "(": pygame.K_LEFTPAREN,
    ")": pygame.K_RIGHTPAREN,
    "#": pygame.K_HASH,
    "&": pygame.K_AMPERSAND,
    ";": pygame.K_SEMICOLON,
    "*": pygame.K_ASTERISK,
    "/": pygame.K_SLASH,
    "@": pygame.K_AT,
    "`": pygame.K_BACKQUOTE,
    "\\": pygame.K_BACKSLASH,
    "_": pygame.K_UNDERSCORE,
    "^": pygame.K_CARET,
    ":": pygame.K_COLON,
    ",": pygame.K_COMMA,
    "$": pygame.K_DOLLAR,
    "=": pygame.K_EQUALS,
    "!": pygame.K_EXCLAIM,
    "-": pygame.K_MINUS,
    ".": pygame.K_PERIOD,
    "+": pygame.K_PLUS,
    "?": pygame.K_QUESTION,
    "'": pygame.K_QUOTE,
    "\"": pygame.K_QUOTEDBL,

    "pagedown": pygame.K_PAGEDOWN,
    "pageup": pygame.K_PAGEUP,
    "return": pygame.K_RETURN,
    "home": pygame.K_HOME,
    "insert": pygame.K_INSERT,
    "scrollock": pygame.K_SCROLLOCK,
    "space": pygame.K_SPACE,
    "sysreq": pygame.K_SYSREQ,
    "tab": pygame.K_TAB,
    "backspace": pygame.K_BACKSPACE,
    "break": pygame.K_BREAK,
    "capslock": pygame.K_CAPSLOCK,
    "clear": pygame.K_CLEAR,
    "delete": pygame.K_DELETE,
    "end": pygame.K_END,
    "escape": pygame.K_ESCAPE,
    "euro": pygame.K_EURO,
    "menu": pygame.K_MENU,
    "mode": pygame.K_MODE,
    "numlock": pygame.K_NUMLOCK,
    "pause": pygame.K_PAUSE,
    "power": pygame.K_POWER,
    "print": pygame.K_PRINT,
    "help": pygame.K_HELP,

# unused values:
# pygame.K_UNKNOWN
# pygame.K_FIRST
# pygame.K_LAST

}
